version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
            - "*"   
        update-types:
          - "patch"
          - "minor"
