name: Benchmark

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Benchmark
        run: |
          cd perf-comparison
          cargo bench
      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion
